# Generated by Django 4.0.1 on 2023-03-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='cardid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
