# Generated by Django 4.0.1 on 2023-03-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_trip_distance_alter_trip_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cardid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
