# Generated by Django 4.0.1 on 2023-03-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_trip_id_alter_userinfo_cardid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='end',
            new_name='end_lat',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start',
            new_name='start_lat',
        ),
        migrations.AddField(
            model_name='trip',
            name='end_lon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_lon',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
