# Generated by Django 4.0.1 on 2023-03-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_end_trip_end_lat_rename_start_trip_start_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='contact',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
