# Generated by Django 4.0.1 on 2023-05-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_trip_bus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='bus_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
