# Generated by Django 4.0.1 on 2023-05-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_trip_bus_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
