# Generated by Django 4.0.1 on 2023-05-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=100)),
                ('bus_name', models.CharField(max_length=100)),
                ('balance', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
