# Generated by Django 4.0.1 on 2023-05-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='bus_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
